### ISSUE TITLE
Keren Gan aplikasinya

### ISSUE THREAD

**Issue by aacassandra** [zahidin/web-aplikasi-inventory-gudang#1]
keren gan aplikasinya

**Comment by rendiaziz** [comment]
maaf bang mau tanya. ini pake xampp versi berapa?

**Comment by aacassandra** [comment]
ga ada requirentment versi xampp. bisa kok. apa ada kendala?

**Comment by rendiaziz** [comment]
![image](https://user-images.githubusercontent.com/55143256/72593685-2e8a7880-3938-11ea-99ce-cfe3fdebe559.png)

bject not found!
The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404
localhost
Apache/2.4.34 (Win32) OpenSSL/1.0.2o PHP/5.6.38



ini cara mengatasi nya gi mana? ini keadaan setelah login, mohon minta pencerahan nya terimakasih banyak

**Comment by KatasandiDev** [comment]
di confignya ganti webgudang menjadi nama foldernya. biasanya erornya karena nama foldernya gk sama dgn yg di config

**Comment by zahidin** [comment]
Terimakasih mas @aacassandra  dan @KatasandiDev yang sudah mau membantu 👍

**Comment by aacassandra** [comment]
> Terimakasih mas @aacassandra dan @KatasandiDev yang sudah mau membantu 👍

followback ya..
