### ISSUE TITLE
Data keluarnya

### ISSUE THREAD

**Issue by arifsmkn** [zahidin/web-aplikasi-inventory-gudang#2]
Bang data keluarnya gx bisa ya

**Comment by b4bonz1020** [comment]
baru input barang keluar 1 x ,setelah itu tidak bisa lagi ini gabaimana ya gan caranya

**Comment by zahidin** [comment]
Bisa di ss mungkin kalo ada error atau yang lain

**Comment by zahidin** [comment]
ini gaada update saya anggep clear ya
