### ISSUE TITLE
Objek Not found!

### ISSUE THREAD

**Issue by rendiaziz** [zahidin/web-aplikasi-inventory-gudang#3]
![image](https://user-images.githubusercontent.com/55143256/72595259-f9802500-393b-11ea-9a94-c2d5027ac93f.png)

cara mengatasi nya gimana teman teman?

**Comment by wahyuandhikaaa** [comment]
same problem here..

mungkin ga karena beda versi xampp nya?
atau karena belom install tools CodeIgniter?

**Comment by rendiaziz** [comment]
install tools codelgniter nya gi mana bang?

Pada tanggal Min, 5 Apr 2020 pukul 10.04 wahyuandhikaaa <
notifications@github.com> menulis:

**Comment by KatasandiDev** [comment]
> ![image](https://user-images.githubusercontent.com/55143256/72595259-f9802500-393b-11ea-9a94-c2d5027ac93f.png)
> 
> cara mengatasi nya gimana teman teman?

Coba cek nama foldernya mas di aplication-config biasanya erorrnya karena itu. Contohnya $config['base_url'] = 'http://localhost/gudang-test-master'

**Comment by KatasandiDev** [comment]
karena defaultnya nama foldernya webgudang. ganti aja jadi nama foldernya

**Comment by zahidin** [comment]
Terimakasih bantuannya mas @KatasandiDev 
Maaf kalo saya telat respon karna kesibukan di real life hahaha
