### ISSUE TITLE
Tidak bisa login

### ISSUE THREAD

**Issue by adit-ads** [zahidin/web-aplikasi-inventory-gudang#4]
![image](https://user-images.githubusercontent.com/76478290/116818567-43733580-ab96-11eb-947b-5e3e2de89107.png)

![image](https://user-images.githubusercontent.com/76478290/116818601-71f11080-ab96-11eb-83a7-d5300449e93c.png)

Sehabis input username dan password tidak bisa ya,, mohon pencerahannya

**Comment by zahidin** [comment]
Apa sudah disesuaikan base_url nya mas  @adit-ads ? jika belum bisa di sesuaikan di folder application/config/config.php

**Comment by zahidin** [comment]
ini gaada update saya anggep clear ya
