### ISSUE TITLE
Tidak bisa login 

### ISSUE THREAD

**Issue by BagasPrastiyo05** [zahidin/web-aplikasi-inventory-gudang#6]
![login](https://user-images.githubusercontent.com/102411741/192154730-548dca2b-d592-4c4f-af55-4010ed5ac621.png)
![error](https://user-images.githubusercontent.com/102411741/192154740-bb08f4b3-fd5d-48aa-9cc4-6c189a7d1f81.png)

**Comment by BagasPrastiyo05** [comment]
untuk base url sudah saya sesuaikan tapi masih tidak bisa

**Comment by zahidin** [comment]
disesuaikan dengan nama yang ada di folder htdocsnya, dan jangan lupa dibagian `base_url ` didalam folder `application/config.php` disesuaikan juga namanya `base_url` dengan nama folder di htdocs

contoh:
`htdocs/test `
maka base_urlnya harus seperti ini 
`http://localhost/test`

**Comment by zahidin** [comment]
ini karna gaada update saya anggep clear ya
