### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by pratama003** [zahidin/web-aplikasi-inventory-gudang#7]
![image](https://user-images.githubusercontent.com/124648252/217138155-4eb56e36-7698-4cb5-8741-5f30f9fb132c.png)
mohon solusinya bang

**Comment by Niuwbee** [comment]
Tinggal ganti versi PHP saja mas

**Comment by zahidin** [comment]
terimakasih mas bantuannya @Niuwbee . ini karna versi php nya sudah ketinggian jadi bisa install versi php 7 atau 5 saja mas @pratama003
