### ISSUE TITLE
cetak pdf tidak bisa

### ISSUE THREAD

**Issue by sm4rtschool** [zahidin/web-aplikasi-inventory-gudang#8]
bang ada solusi ngga..saya pake php 7.4.29..sudah saya upgrade library tcpdf nya..muncul error Message: require_once(/Applications/XAMPP/xamppfiles/htdocs/inventory-gudang-master/application/libraries/tcpdf/tcpdf.php): failed to open stream: No such file or directory

**Comment by zahidin** [comment]
itu ga ketemu mas path nya, udah coba di cek kah pathnya dengan benar untuk lokasi tcpdf.php nya ?

**Comment by zahidin** [comment]
ini gaada update saya anggep clear ya
